name: Deploy Cloud Function to GCP 

on:
  push:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v2
       

     - name: Find out what branch is beigned pushed 
       run: echo '::set-output name=SELECTED_COLOR::green'
       
     - name: run a normal command
       run: echo 'Hello world'

     - name: git the branches 
       run: git branch -r 
       
